package in.ineuron.main;

import in.ineuron.controller.IProductController;
import in.ineuron.factory.ProductControllerFactory;
import in.ineuron.pojo.Product;

public class TestApp
{

	private static IProductController productController = ProductControllerFactory.getProductController();

	public static void main(String[] args)
	{
		// for handling all user inputs
		UserInputHandler userInputHandler = UserInputHandler.getUserInputHandler();
		int autoGeneratedProductId = 0;

		while (true)
		{
			int userChoice = userInputHandler.getUserChoice();

			switch (userChoice)
			{
			case 1:
				// creating Pojo class object and setting data for insert
				Product productForAdd = userInputHandler.getAddProdutInput();

				System.out.println(productForAdd);

				// passing to controller
				autoGeneratedProductId = productController.addProduct(productForAdd);

				if (autoGeneratedProductId == 0)
				{
					System.out.println("\n\n==================================================\n\n");
					System.err.println("Oops....Something Went wrong............");
					System.err.println("Insert Operation failed");
					System.out.println("\n\n==================================================\n\n");
				} else
				{
					System.out.println("\n\n==================================================\n\n");
					System.out.println("product details inserted Successfully");
					System.out.println("please take a note of Product Id: " + autoGeneratedProductId);
					System.out.println("\n\n==================================================\n\n");
				}

				break;

			case 2:

				break;
			case 3:

				break;
			case 4:

				break;

			default:
				break;
			}
		}

	}
}
